
[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Angus Hollands", email = "goosey15@gmail.com"},
]
dependencies = [
    "jupyterlab>=4",
    "jupyterlab-myst>=2",
]
requires-python = ">=3.10"
license = {text = "MIT"}
